# -*- coding: utf-8 -*-
"""inbound_scanning

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vjEJf4NsxSoqZYtpGaD9aRvKBqb5GWT4
"""

# Import dependencies
import time
import csv
import collections as col

import pandas as pd
import re



# The mcr.txt path on Rover will be:
# C:\Users\Paladin User\Google Drive\King Ace Hardware\Inbound Scanning

# Create and format the dataframe
df = pd.read_csv("MasterCrossReference.txt")
df['OrderQty'] = df['OrderQty'].astype(int)
df = df.astype(str)
df['Count'] = ""
df['OK'] = ""
df = df.sort_values(by=['Deliverable Unit'], ascending=False)
# Create other dataframes for later reporting
dfshorts = pd.DataFrame(columns=df.columns)
dfovers = pd.DataFrame(columns=df.columns)

# Create empty list for UPC scans
scanned_items = []

#mcrdf.head()

#Basic interface decision tree.
#Most common loop is scanning items.
#Also accepts inputs for report generation, etc.
while True:
    print('Please scan an item. Enter "exit" to finalize and generate report.')
    scanned = input()
    scanned = scanned.lstrip('0')
    if scanned == 'help':
        print('''\tEnter 'short' to generate a shortage report.
        Enter 'over' to generate an overage report.
        Enter 'exit' to exit this awesome program.''')
        continue
    if scanned == 'over':
        overage_report()
        continue
    if scanned == 'short':
        shortage_report()
        continue
    if scanned == 'exit':
        break
    else:
        try:
            scanned_items.append(scanned)
            a = df[df['UPC'] == scanned]
            print(a)
            print(f"Item count: {scanned_items.count(scanned)}")
        except ValueError:
            print("That item is not expected.")
            overs.append(scanned)
time.sleep(0)
# c is a Counter object, counting occurences of each UPC in scanned_items
# it is a dictionary with the UPC as the key and the count as the value
c = col.Counter(scanned_items)
# MAP the c values onto the Count column
df['Count'] = df['UPC'].map(c)
# Reset everything to strings to help with later equivalency tests
df = df.astype(str)

#mcrdf.head()

# This is how you iterate over a dataframe.
# Don't forget to use the .index on your dataframe when initializing
# the for loop.
for ind in df.index:
    if df['OrderQty'][ind] > df['Count'][ind]:
        df['OK'][ind] = "SHORT"
    elif df['OrderQty'][ind] < df['Count'][ind]:
        df['OK'][ind] = "OVER"
    else:
        df['OK'][ind] = "OK" 

#mcrdf.head()

#Export one big excel file with filters and formatting
df = df.drop(df[df['OK'] == 'OK'].index)
df['UPC'] = ''
df.sort_values(by=['OK'])
tote = re.compile(r'^T')
df = df[df['Deliverable Unit'].str.match(tote) == True]
df.to_excel('report.xlsx')